# Control file for continuous integration testing at http://travis-ci.org/

language: c
compiler:
  - gcc

os:
  - linux

env:
  global:
    - CODECOV_TOKEN=5550daa1-ef0c-48a7-bc2b-b3107f09e481
  matrix:
    - USE_CONFIG=no
    - USE_CONFIG=yes

# For linux systems
addons:
  apt:
    packages:
    - liblzma-dev
    - libbz2-dev

# For MacOSX systems
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install xz || ( brew update && brew install xz ); fi

script:
  - if test "$USE_CONFIG" = "yes" ; then autoreconf && ./configure ; fi && make -e && make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
